// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private object BatteryOptimizationPigeonPigeonUtils {

    fun wrapResult(result: Any?): List<Any?> {
        return listOf(result)
    }

    fun wrapError(exception: Throwable): List<Any?> {
        return if (exception is FlutterError) {
            listOf(
                exception.code,
                exception.message,
                exception.details
            )
        } else {
            listOf(
                exception.javaClass.simpleName,
                exception.toString(),
                "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
            )
        }
    }
}

private open class BatteryOptimizationPigeonPigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
        return super.readValueOfType(type, buffer)
    }

    override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
        super.writeValue(stream, value)
    }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BatteryOptimizationPigeon {
    /** Returns whether the app is currently *ignored* from battery optimizations. */
    fun isIgnoringBatteryOptimizations(): Boolean

    /** Opens the battery-optimization/settings screen for this app (Android). */
    fun openBatteryOptimizationSettings()

    companion object {
        /** The codec used by BatteryOptimizationPigeon. */
        val codec: MessageCodec<Any?> by lazy {
            BatteryOptimizationPigeonPigeonCodec()
        }

        /** Sets up an instance of `BatteryOptimizationPigeon` to handle messages through the `binaryMessenger`. */
        @JvmOverloads
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: BatteryOptimizationPigeon?,
            messageChannelSuffix: String = ""
        ) {
            val separatedMessageChannelSuffix =
                if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.nl_jknaapen_fladder.settings.BatteryOptimizationPigeon.isIgnoringBatteryOptimizations$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> = try {
                            listOf(api.isIgnoringBatteryOptimizations())
                        } catch (exception: Throwable) {
                            BatteryOptimizationPigeonPigeonUtils.wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.nl_jknaapen_fladder.settings.BatteryOptimizationPigeon.openBatteryOptimizationSettings$separatedMessageChannelSuffix",
                    codec
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        val wrapped: List<Any?> = try {
                            api.openBatteryOptimizationSettings()
                            listOf(null)
                        } catch (exception: Throwable) {
                            BatteryOptimizationPigeonPigeonUtils.wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}
